CREATE TABLE IF NOT EXISTS endpoint_accesses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_name VARCHAR(100) NOT NULL,
    uri_path VARCHAR(512) NOT NULL,
    client_ip VARCHAR(45) NOT NULL,
    access_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_access_timestamp ON endpoint_accesses(access_timestamp);
CREATE INDEX IF NOT EXISTS idx_uri_access ON endpoint_accesses(uri_path, access_timestamp);
CREATE INDEX IF NOT EXISTS idx_app_uri ON endpoint_accesses(application_name, uri_path);